# Generated by Django 5.0.4 on 2024-05-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0002_goods_slug_alter_goods_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name_plural': 'Goods'},
        ),
        migrations.AlterField(
            model_name='goods',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
